version: '3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - r_db:/var/lib/mysql
    ports:
      - "33069:3306"
  app:
    depends_on:
      - db
    build: ./
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - JWT_SECRET=$JWT_SECRET
    stdin_open: true
    tty: true

volumes:
  r_db:

